language: objective-c
osx_image: xcode10.1
xcode_workspace: KZ.xcworkspace
xcode_scheme: KZ

before_install:
  - brew install swiftlint
  - gem install cocoapods --pre

matrix:
    include:
        - os: osx
          osx_image: xcode10.1
          env:
            - TASK=lintpod
              SWIFT_VERSION=4.2

script:
  - rake ci:$TASK

branches:
  only:
    - master
