language: objective-c
osx_image: xcode8
xcode_workspace: KZ.xcworkspace
xcode_scheme: KZ

before_install:
  - brew install swiftlint
  - gem install cocoapods --pre

matrix:
    include:
        # Swift 3.0
        - os: osx
          osx_image: xcode8
          env:
            - TASK=lintpod
              SWIFT_VERSION=3.0

script:
  - rake ci:$TASK

branches:
  only:
    - master
